name: Update Twitter Banner

on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: |
          npm run start
          git config user.name baumannzone
          git config user.email jorge.baumann.aguilar@gmail.com
          fecha=`date +'%Y_%m_%d-%H:%M'`
          mv img/1500x500.png generated-img/${fecha}.png
          git add generated-img/*
          git commit -m "[Bot] Add image :bowtie:"
          git push origin main
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
